### ISSUE TITLE
PHP Warning: file_exists(): open_basedir restrictio after update to TYPO3 13.4.2

### ISSUE THREAD

**Issue by mediaessenz** [quellenform/t3x-iconpack#32]
I see a lot of errors after updating the TYPO3 of a page to 13.4.2 which uses EXT:iconpack, EXT:bootstrap_package_iconpack and EXT:iconpack_bootstrap:
```
Core: Error handler (BE): PHP Warning: file_exists(): open_basedir restriction in effect. File(/_assets/9c2af0425aa913aac0cdcdf6f61dc0dd/Vendor/icons-1.11.1/font/bootstrap-icons.css) is not within the allowed path(s): (/var/www/vhosts/my-domain.tld/:/tmp/) in /var/www/vhosts/my-domain.tld/httpdocs/production/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php line 2037
```
I think the root is somewhere in the IconpackUtility::getStreamlinedFileName method of EXT:iconpack.

**Comment by stephankellermayr** [comment]
@mediaessenz Since I cannot reproduce the error, the method was largely adopted directly from the [core](https://github.com/TYPO3/typo3/blob/df26f30c757735a42453bb12897ea6df86086d3f/typo3/sysext/core/Classes/Page/PageRenderer.php#L2025), and the error message actually says something else (*"open_basedir restriction in effect"*), I suspect an error in your installation.

Please investigate the problem in more detail and report what else you were able to find out.

**Comment by mediaessenz** [comment]
Found the issue (open base dir restiction) on my side.
